language: elixir

elixir:
  - 1.8.1
  - 1.6.0

before_script:
  - mix credo --strict
  # - mix dialyzer

script: mix test --exclude gnuplot:true

# Remove 6min delay downloading Dialyzer dependencies
# cache:
#   directories:
#     - _build
#     - deps  

after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  